version: '3'

services:

    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=devops"
            - "MYSQL_PASSWORD=devops"
            - "MYSQL_DATABASE=demo_meetup"
