version: '3'

services:

    web:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ".:/home/docker"
            - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
        networks:
            - demo_meetup

    php:
        build:
            context: docker/
        volumes:
            - "./src:/home/docker"
            - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        networks:
            - demo_meetup
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"

    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - "./.data/db:/var/lib/mysql"
        networks:
            - demo_meetup
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        networks:
            - demo_meetup
        environment:
            - "PMA_HOST=db"
            - "PMA_USER=root"
            - "PMA_PASSWORD=root"

networks:
    demo_meetup:
        driver: bridge
