FROM nginx
# FROM nginx:1.12

COPY index.html /usr/share/nginx/html

# Build l'image et la tagger
# docker build -t nginx:demo_meetup .

# Voir les images docker :
# docker images

# Lancement du container à partir de l'image
# docker run -d --name web -p 8080:80 nginx:demo_meetup

# Visiter http://localhost:8080

# Voir les logs de Nginx
# docker logs web

# ---

# Stoper le container
# docker stop web

# Supprimer le container
# docker rm web

# Supprimer les images
# docker rmi nginx:demo_meetup nginx:latest
